# Generated by Django 5.2.11 on 2026-03-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('base_prices', models.JSONField(blank=True, default=dict, help_text='Base ticket prices by day type')),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('actors', models.JSONField(blank=True, default=list)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('producers', models.JSONField(blank=True, default=list)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('synopsis', models.TextField(blank=True, help_text='Primary synopsis to display', null=True)),
                ('all_synopsis', models.JSONField(blank=True, default=dict)),
                ('all_urls', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='movies_movi_title_652549_idx'), models.Index(fields=['age'], name='movies_movi_age_707c18_idx')],
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('cinema', models.CharField(blank=True, max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='movies.theater')),
            ],
            options={
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['movie', 'date'], name='movies_show_movie_i_ed1027_idx'), models.Index(fields=['theater', 'date'], name='movies_show_theater_f55481_idx'), models.Index(fields=['date', 'time'], name='movies_show_date_03ed69_idx')],
                'unique_together': {('movie', 'theater', 'date', 'time', 'cinema', 'format')},
            },
        ),
    ]
