# Generated by Django 5.2.11 on 2026-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='theaters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
