# Generated by Django 5.2.11 on 2026-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_theaters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
