# Generated by Django 5.2.11 on 2026-04-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_theater_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showing',
            unique_together={('movie', 'theater', 'date', 'time', 'format')},
        ),
        migrations.RemoveField(
            model_name='showing',
            name='cinema',
        ),
    ]
