# Generated by Django 5.2.11 on 2026-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_showing_unique_together_remove_showing_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
    ]
